jobs:
- job: Publish_Nuget
  displayName: Publish Nuget packages
  condition: and(succeeded(), eq(variables['DoNuget'], 'true'))

  pool:
    vmName: win2016-vs2017

  workspace:
    clean: all

  steps:
  - checkout: none

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifact: nuget'
    inputs:
      artifactName: nuget
      downloadPath: $(Build.BinariesDirectory)

  - task: NuGetCommand@2
    displayName: Push packages
    condition: and(succeeded(), eq(variables['SigningCertificate'], 'Python Software Foundation'))
    inputs:
      command: push
      packagesToPush: $(Build.BinariesDirectory)\nuget\*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'Python on Nuget'
