jobs:
- job: Publish_Store
  displayName: Publish Store packages
  condition: and(succeeded(), eq(variables['DoMSIX'], 'true'))

  pool:
    vmName: win2016-vs2017

  workspace:
    clean: all

  steps:
  - checkout: none

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifact: msixupload'
    inputs:
      artifactName: msixupload
      downloadPath: $(Build.BinariesDirectory)

  # TODO: eq(variables['SigningCertificate'], 'Python Software Foundation')
  # If we are not real-signed, DO NOT PUBLISH
