name: Release_$(Build.SourceBranchName)_$(SourceTag)_$(Date:yyyyMMdd)$(Rev:.rr)

# QUEUE TIME VARIABLES
# variables:
#   GitRemote: python
#   SourceTag:
#   DoPGO: true
#   SigningCertificate: 'Python Software Foundation'
#   SigningDescription: 'Built: $(Build.BuildNumber)'
#   DoLayout: true
#   DoMSIX: true
#   DoNuget: true
#   DoEmbed: true
#   DoMSI: true
#   DoPublish: false

trigger: none
pr: none

stages:
- stage: Build
  displayName: Build binaries
  jobs:
  - template: windows-release/stage-build.yml

- stage: Sign
  displayName: Sign binaries
  dependsOn: Build
  jobs:
  - template: windows-release/stage-sign.yml

- stage: Layout
  displayName: Generate layouts
  dependsOn: Sign
  jobs:
  - template: windows-release/stage-layout-full.yml
  - template: windows-release/stage-layout-embed.yml
  - template: windows-release/stage-layout-nuget.yml

- stage: Pack
  dependsOn: Layout
  jobs:
  - template: windows-release/stage-pack-nuget.yml

- stage: Test
  dependsOn: Pack
  jobs:
  - template: windows-release/stage-test-embed.yml
  - template: windows-release/stage-test-nuget.yml

- stage: Layout_MSIX
  displayName: Generate MSIX layouts
  dependsOn: Sign
  condition: and(succeeded(), eq(variables['DoMSIX'], 'true'))
  jobs:
  - template: windows-release/stage-layout-msix.yml

- stage: Pack_MSIX
  displayName: Package MSIX
  dependsOn: Layout_MSIX
  jobs:
  - template: windows-release/stage-pack-msix.yml

- stage: Build_MSI
  displayName: Build MSI installer
  dependsOn: Sign
  condition: and(succeeded(), eq(variables['DoMSI'], 'true'))
  jobs:
  - template: windows-release/stage-msi.yml

- stage: Test_MSI
  displayName: Test MSI installer
  dependsOn: Build_MSI
  jobs:
  - template: windows-release/stage-test-msi.yml

- stage: PublishPyDotOrg
  displayName: Publish to python.org
  dependsOn: ['Test_MSI', 'Test']
  condition: and(succeeded(), eq(variables['DoPublish'], 'true'))
  jobs:
  - template: windows-release/stage-publish-pythonorg.yml

- stage: PublishNuget
  displayName: Publish to nuget.org
  dependsOn: Test
  condition: and(succeeded(), eq(variables['DoPublish'], 'true'))
  jobs:
  - template: windows-release/stage-publish-nugetorg.yml

- stage: PublishStore
  displayName: Publish to Store
  dependsOn: Pack_MSIX
  condition: and(succeeded(), eq(variables['DoPublish'], 'true'))
  jobs:
  - template: windows-release/stage-publish-store.yml
